POST https://node-do-zero-48vh.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###

GET https://node-do-zero-48vh.onrender.com/videos

###

PUT https://node-do-zero-48vh.onrender.com/videos/a17c29fd-dfca-4152-8a61-4af136e8bdc4
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse é o segundo video",
  "duration": 180
}

###

DELETE https://node-do-zero-48vh.onrender.com/videos/d9c6d88f-826f-4236-ac4e-84f6bf997d9d
